cask_args appdir: '/Applications'

tap 'homebrew/bundle'
# tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'docker'
brew 'docker-compose'
brew 'jq'
brew 'openssl'
brew 'pwgen'
brew 'readline'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

brew 'node'
brew 'pyenv'
brew 'yarn'

brew 'postgresql'
brew 'redis'

cask 'boostnote'
cask 'brave-browser'
cask 'cyberduck'
cask 'dropbox'
cask 'docker'
cask 'firefox'
cask 'flux'
cask 'free-download-manager'
cask 'gnucash'
cask 'iterm2'
cask 'lektor'
cask 'libreoffice'
cask 'megasync'
cask 'pgadmin4'
cask 'postman'
cask 'seashore'
cask 'skype'
cask 'slack'
cask 'transmission'
cask 'vagrant'
cask 'vlc'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'visual-studio-code'


# brew 'go'
# brew 'grc'
# brew 'imagemagick'
# brew 'jp2a'
# brew 'jq'
# brew 'libcaca', args: ['with-imlib2']
# brew 'libgit2'
# brew 'puma/puma/puma-dev'
# brew 'roundup'
# brew 'spaceman-diff'
# brew 'spark'
# cask '1password'
# cask 'adium'
# cask 'garmin-express'
# cask 'handbrake'
# cask 'mapbox-studio'
# cask 'steam'
# cask 'tunnelbear'
