import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.85

[font]
size = 16

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

