[settings]
experimental = true
python_compile = true
go_set_gobin = false
idiomatic_version_file_enable_tools = ["python"]

[tools]
ruby = "2.7"
python = "3.14"
node = "24.10"
deno = "2.5"
rust = "1.90"
terraform = "1.13"
task = "3.45"
jq = "latest"
sqlite = "3.50"
maven = "latest"
go = "1.25"
air = "1.63"
uv = "0.9"
zig = "0.15"
pipx = "latest"
pnpm = "10.18"
golangci-lint = "2.5"
pre-commit = "4.3"
just = "1.43"
ripgrep = "15.0"
grpcurl = "1.9"
ffmpeg = "8.0"
gcloud = "543.0.0"
stylua = "latest"
firebase = "14.20"
cookiecutter = "2.6"
ruff = "0.14"
bat = "0.26"
zoxide = "0.9"
fzf = "0.66"
starship = "1.23"
helm = "3.19"
lsd = "1.2"
cloud-sql-proxy = "2.18"
ollama = "0.12"
jujutsu = "0.34"
curlie = "1.8"
typst = "0.13"
jless = "0.9"

[env]

