[settings]
experimental = true
python_compile = true
go_set_gobin = false
idiomatic_version_file_enable_tools = ["python"]

[tools]
ruby = "2.7"
python = "3.13"
node = "24.7"
deno = "2.4"
rust = "1.89"
terraform = "1.13"
task = "3.44"
jq = "latest"
sqlite = "3.50"
maven = "latest"
go = "1.25"
air = "1.62"
uv = "0.8"
zig = "0.15"
pipx = "latest"
pnpm = "10.15"
golangci-lint = "2.4"
pre-commit = "4.3"
just = "1.42"
ripgrep = "14.1"
grpcurl = "1.9"
ffmpeg = "8.0"
gcloud = "536.0.1"
stylua = "latest"
firebase = "14.15"
cookiecutter = "2.6"
ruff = "0.12"
bat = "0.25"
zoxide = "0.9"
fzf = "0.65"
starship = "1.23"
helm = "3.18"
lsd = "1.1"
cloud-sql-proxy = "2.18"

[env]

