alias d='docker $*'
alias d-c='docker-compose $*'
alias d-prune='docker image prune -f && docker container prune -f'
alias d-rmi-dangle='docker rmi $(docker images -f "dangling=true" -q)'
alias d-c-d='docker-compose -f docker-compose.dev.yml $*'
alias d-c-dd='docker-compose -f docker-compose.yml -f docker-compose.dev.yml $*'
alias d-c-dt='docker-compose -f docker-compose.yml -f docker-compose.test.yml $*'

alias d-i='docker image $*'
alias d-n='docker network $*'
alias d-v='docker volume $*'
