[settings]
experimental = true
python_compile = true
go_set_gobin = false

[tools]
ruby = "2.7"
python = "3.12"
node = "20.17"
deno = "1.45"
rust = "1.80"
terraform = "1.10"
task = "3.41"
jq = "latest"
sqlite = "latest"
maven = "latest"
go = "1.23"
air = "1.61"
uv = "0.5"
chezmoi = "2.58"
poetry = "1.8"
zellij = "0.40"
zig = "0.13"
pipx = "latest"
pnpm = "10.1"
golangci-lint = "1.63"
pre-commit = "4.1"
just = "1.39"
ripgrep = "14.1"
grpcurl = "1.9"
ffmpeg = "7.1"
gcloud = "513.0.0"
stylua = "latest"
firebase = "13.33"

[env]

