[settings]
experimental = true
python_compile = true
go_set_gobin = false

[tools]
ruby = "2.7"
python = "3.12"
node = "20.16"
deno = "1.45"
rust = "1.80"
terraform = "1.9"
helm = "3.15"
pnpm = "9.6"
task = "3.38"
jq = "latest"
sqlite = "latest"
ripgrep = "latest"
pre-commit = "latest"
maven = "latest"
go = "1.23"
golangci-lint = "1.61"
air = "1.52"
uv = "0.4"
chezmoi = "2.52"
poetry = "1.8"
grpcurl = "1.9.1"

