[settings]
experimental = true
python_compile = true
go_set_gobin = false
idiomatic_version_file_enable_tools = ["python"]

[tools]
ruby = "2.7"
python = "3.12"
node = "20.19"
deno = "1.45"
rust = "1.80"
terraform = "1.10"
task = "3.41"
jq = "latest"
sqlite = "3.49"
maven = "latest"
go = "1.24"
air = "1.61"
uv = "0.5"
chezmoi = "2.58"
zig = "0.13"
pipx = "latest"
pnpm = "10.1"
golangci-lint = "2.1"
pre-commit = "4.1"
just = "1.39"
ripgrep = "14.1"
grpcurl = "1.9"
ffmpeg = "7.1"
gcloud = "513.0.0"
stylua = "latest"
firebase = "13.33"
cookiecutter = "2.1"
ruff = "0.9"
bat = "0.25"

[env]

